// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPostgreSQL.Models;

#nullable disable

namespace WebPostgreSQL.Migrations
{
    [DbContext(typeof(DbContextAplicacao))]
    [Migration("20240909152723_NovasColunasProduto")]
    partial class NovasColunasProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPostgreSQL.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Nascimento");

                    b.Property<string>("SISBOV")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SISBOV");

                    b.HasKey("Id");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.OrdenhaAnimal", b =>
                {
                    b.Property<int>("OrdenhaId")
                        .HasColumnType("integer");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.HasKey("OrdenhaId", "AnimalId");

                    b.HasIndex("AnimalId");

                    b.ToTable("OrdenhaAnimais");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.RegistroOrdenha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOrdenha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataOrdenha");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VolumeLeite")
                        .HasColumnType("numeric")
                        .HasColumnName("VolumeLeite");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroOrdenha");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PassWord");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.OrdenhaAnimal", b =>
                {
                    b.HasOne("WebPostgreSQL.Models.Animal", "Animal")
                        .WithMany("OrdenhaAnimais")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPostgreSQL.Models.RegistroOrdenha", "Ordenha")
                        .WithMany("OrdenhaAnimais")
                        .HasForeignKey("OrdenhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Ordenha");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.RegistroOrdenha", b =>
                {
                    b.HasOne("WebPostgreSQL.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.Animal", b =>
                {
                    b.Navigation("OrdenhaAnimais");
                });

            modelBuilder.Entity("WebPostgreSQL.Models.RegistroOrdenha", b =>
                {
                    b.Navigation("OrdenhaAnimais");
                });
#pragma warning restore 612, 618
        }
    }
}
